version: '3'

services:
        web:
                build:
                  # folder to look in for project or build context
                  context: .
                  dockerfile: Dockerfile.dev
                ports:
                  - "3000:3000"
                volumes:
                  - /app/node_modules
                  - web_ui_cache:/root/.npm
                  - .:/app
volumes:
        web_ui_cache:

